[package]
name = "roar"
version = "0.1.0"
authors = ["Erich Healy <ErichRHealy@gmail.com>"]
edition = "2018"

[lib]
name = "roar"
path = "src/lib.rs"

[[bin]]
name = "roar"
path = "src/bin.rs"

[dependencies]
futures-preview = { version = "0.3.0-alpha.18", features = ["async-await", "nightly" ]}
async-std = "0.99"
clap = "2.33"
failure = "*"
byteorder = "1"
crc = "1"
bitflags = "*"
num = "0.2"
num-derive = "0.2"
num-traits = "0.2"

#clap = "2.32"
#num = "0.2"
#num-derive = "*"
#num-traits = "*"
#byteorder = "1"
#bitflags = "*"
#failure = "*"
#crc = "1"
#tokio = { version = "0.1.15", features = ["async-await-preview"] }
